# Conda环境名称
name: spectra

# 依赖库的下载通道，conda-forge是社区维护的、非常全面的通道
channels:
  - pytorch
  - conda-forge
  - defaults

# 具体的依赖库列表
dependencies:
  # 核心环境
  - python=3.10

  # 深度学习框架 (我们指定从pytorch通道下载，并选择CPU版本，因为您在Mac上)
  - pytorch::pytorch
  - pytorch::cpuonly 
  
  # 数据处理与科学计算
  - pandas
  - pyarrow       # 高效读写Parquet文件
  - numpy
  
  # 化学信息学
  - conda-forge::rdkit  # 明确指定从conda-forge通道下载RDKit
  
  # 工具与可视化
  - matplotlib
  - seaborn
  - tqdm          # 优雅的进度条
  - pyyaml        # 用于加载我们的.yaml配置文件
  - jupyterlab    # 用于运行notebooks
  
  # 实验跟踪
  - wandb           # 强烈推荐的实验管理工具
  
  # pip包管理器 (以备不时之需)
  - pip