# 数据参数
data_path: "data/processed/train_data.pt"
max_peaks: 512
peak_vector_dim: 12

# 模型参数
model_name: "SetTransformer"
hidden_dim: 256
num_heads: 8

# 训练参数
learning_rate: 0.0001
batch_size: 64
epochs: 100

# wandb参数
project_name: "ms-nmr-pretrain"
run_name: "set_transformer_v1_baseline"
