# --- 实验参数 ---
experiment:
  seed: 42 # 用于复现实验结果的随机种子

# --- 数据集参数 ---
data:
  processed_dir: "data/processed"
  val_split_ratio: 0.1 # 验证集划分比例
  max_peaks: 512
  masking_fraction: 0.15
  num_workers: 4 # 恢复为多进程数据加载

# --- 特征维度定义 (用于损失函数计算) ---
# 避免在代码中硬编码索引
feature_slices:
  modality: [0, 2]       # 模态ID (one-hot)
  numerical: [2, 6]      # 4个连续数值特征
  multiplicity: [6, 12]  # 多重性 (one-hot)

# --- 模型参数 ---
model:
  dim_input: 12
  dim_output: 12
  dim_hidden: 256
  num_heads: 8
  num_inds: 32
  depth: 6
  ln: True

# --- 训练参数 ---
training:
  device: "cuda:1" # [修改] 指定使用1号GPU
  epochs: 5 # [修改] 先设置一个较小的epoch数以便快速验证
  batch_size: 4  # [确认] 使用较小的批量大小
  learning_rate: 0.0001
  checkpoint_dir: "checkpoints" # 保存模型检查点的目录
  
# --- 实验管理 ---
wandb:
  project_name: "ms-nmr-pretrain"
  run_name: "set-transformer-v1-gpu1-testrun" # [修改] 修改为本次测试的实验名称